<p style="font-size: 16px;">Filter List</p>
<form method="get" action="/members/index/">
    <ul class="form" style="margin-bottom: 10px; overflow: hidden;">
        <li>
            <div style="float: left; margin-right: 10px;">
                <label class="desc">Name</label>
                <input type="text" name="name" value="<?=!empty($this->filter['name']) ? $this->filter['name'] : ''?>" />
            </div>
            
            <div style="float: left; margin-right: 10px;">
                <label class="desc">Art Form</label>
                <select name="artform">
                    <option value="">- select -</option>
                    <?=Globals::makeOptions($this->artforms, $this->filter['artform'])?>
                </select>
            </div>
            
            <div style="float: left; margin-right: 10px;">
                <label class="desc">Activity</label>
                <select name="activity">
                    <option value="">- select -</option>
                    <?=Globals::makeOptions($this->activities, $this->filter['activity'])?>
                </select>
            </div>
            
            <div style="float: left; margin-right: 10px;"><label class="desc">&nbsp;</label><input type="submit" value="Submit"></div>
        </li>
    </ul>
</form>
<p style="font-size: 14px; margin-bottom: 20px; clear: both;" id="alphabet">
<?php foreach(range('a','z') as $i): ?>
    <a href="/members/index/filter-char/<?=$i?>"<?php if($this->showall == $i): ?> class="current"<?php endif; ?>><?=$i?></a> <?php if($i != 'z'): ?>|<?php endif; ?>
<?php endforeach; ?>
<?php if($this->showall): ?>
| <a href="/members">show all</a>
<?php endif; ?>
</p>
<table cellspacing="5" id="artist_listing">
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Status</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($this->membersList as $members): ?>
    <tr>
        <td><?=$members['first_name']?> <?=$members['surname']?></td>
        <td><?=$members['email']?></td>
        <td width="80px;"><?=$members['status']?></td>
        <td width="300px"><?php if($members['status'] == 'approved'): ?><a href="/members/memberInfo/id/<?=$members['id']?>" class="button">Edit</a><?php endif; ?><a href="/members/delete/id/<?=$members['id']?>" class="button">Delete</a><?php if($members['status'] !== 'approved'): ?><a href="/members/approve/id/<?=$members['id']?>" class="button">Approve</a> <a href="/members/reject/id/<?=$members['id']?>" class="button">Reject</a><?php endif; ?></td>
    </tr>
    <?php endforeach; ?>
</table>
