<p><img src="/images/artist_header.jpg" alt="Artist" width="747" height="52" /></p>

<h2 class="artistname"><?=$this->artist['first_name']?> <?=$this->artist['surname']?></h2>

<p id="artist_nav"><a href="/artists/biography/id/<?=$this->artist['id']?>"><img src="/images/artist_biography.jpg" alt="Biography" width="177" height="28" /></a> <a href="/artists/news/id/<?=$this->artist['id']?>"><img src="/images/artist_news.jpg" alt="News" width="177" height="28" /></a> <a href="/artists/viewartist/id/<?=$this->artist['id']?>"><img src="/images/artist_artwork.jpg" alt="Artwork" width="177" height="28" /></a></p>

<form method="post" action="/artists/savenews/">      
     
    <ul class="form">
        <li>
            <label class="desc">Title</label>
            <input type="text" name="title"/>
        </li>
        <li>
            <label class="desc">Previes</label>
            <input type="text" name="preview"/>
        </li>
        <li>
            <label class="desc">Content</label>
            <textarea name="content"></textarea>
        </li>
        <li>
            <input type="submit" name="submitbutton" value="Create"/>
        </li>
    </ul>

</form>