<p><img src="/images/artist_header.jpg" alt="Artist" width="747" height="52" /></p>

<h2 class="artistname"><?=$this->artist['first_name']?> <?=$this->artist['surname']?></h2>

<p id="artist_nav"><a href="/artists/biography/id/<?=$this->artist['id']?>"><img src="/images/artist_biography.jpg" alt="Biography" width="177" height="28" /></a> <a href="/artists/news/id/<?=$this->artist['id']?>"><img src="/images/artist_news.jpg" alt="News" width="177" height="28" /></a> <a href="/artists/viewartist/id/<?=$this->artist['id']?>"><img src="/images/artist_artwork.jpg" alt="Artwork" width="177" height="28" /></a></p>

<?php if($this->work): ?>
    <?php foreach($this->work as $work): ?>
        <div class="artistswork">
            <div class="artwork_info">
                <h3><?=$work['title']?></h3>
                <?php if($work['credits']): ?>
                    <p class="artwork_credits"><?=$work['credits']?></p>
                <?php endif; ?>
                <?php if($work['size']): ?>
                    <p class="artwork_credits">Size of work: <?=$work['size']?></p>
                <?php endif; ?>
                <?php if($work['price']): ?>
                    <p class="artwork_credits">Price: <?=$work['price']?></p>
                <?php endif; ?>
                <img src="/images/artist_uploads/<?=$this->artist['id']?>/<?=$work['picture']?>" width="430" alt="<?=$work['title']?>" />
                <h4 class="artwork_about_header">About this artwork</h4>
                <p class="artwork_about"><?=$work['about_artwork']?></p>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>