<p><img src="/images/artist_header.jpg" alt="Artist" width="747" height="52" /></p>

<h2 class="artistname">
    <?=$this->artist['first_name']?> <?=$this->artist['surname']?>
    <?php if($this->profileOwner): ?>
    <span><a href="/artists/editprofile/id/<?=$this->artist['id']?>" title="edit profile">edit profile</a></span>
    <?php endif; ?>    
</h2>


<p id="artist_nav"><a href="/artists/biography/id/<?=$this->artist['id']?>"><img src="/images/artist_biography.jpg" alt="Biography" width="177" height="28" /></a> <a href="/artists/news/id/<?=$this->artist['id']?>"><img src="/images/artist_news.jpg" alt="News" width="177" height="28" /></a> <a href="/artists/viewartist/id/<?=$this->artist['id']?>"><img src="/images/artist_artwork.jpg" alt="Artwork" width="177" height="28" /></a></p>

<h3>Artist statement</h3>
<?=$this->artist['statement']?>

<h3>Other experience</h3>
<?=$this->artist['other_experience']?>

<?php if($this->artforms): ?>
<h3>Artforms</h3>
<ul>
    <?php foreach($this->artforms as $artform): ?>
        <li><?=$artform['artform']?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<?php if($this->work): ?>
<h3>Artwork</h3>
<?=$this->work['title']?><br />
<a href="/artists/viewartist/id/<?=$this->work['artist_id']?>"><img src="/images/artist_uploads/<?=$this->work['artist_id']?>/<?=$this->work['picture']?>" alt="<?=$this->work['title']?>" width="150" /></a>
<?php endif; ?>