<?php

    echo '<strong>Welcome ' . $this->artist['name'] . ' your details are as followed</strong><br/><br/>';         
       
    echo '
    <form method="post" action="/artist/update/">
    <input type="hidden" name="id" value="' . $_SESSION['id'] . '"/>
    <input type="text" name="first_name" value="' . $this->artist["first_name"] . '"/> First Name <br/>
    <input type="text" name="surname" value="' . $this->artist["surname"] . '"/> Surname <br/>';
    if(!empty($this->artist['organisation'])): echo '<input type="text" name="organisation" value="' . $this->artist["organisation"] . '"/> Organisation <br/>'; endif;    
    echo '<input type="text" name="addressOne" value="' . $this->address["lineOne"] . '"/> Address line one <br/>
    <input type="text" name="addressTwo" value="' . $this->address["lineTwo"] . '"/> Address line two <br/>
    <input type="text" name="city" value="' . $this->address["city"] . '"/> City <br/>
    <input type="text" name="county" value="' . $this->address["county"] . '"/> County <br/>
    <input type="text" name="country" value="' . $this->address["country"] . '"/> Country <br/>
    <input type="text" name="telephone" value="' . $this->artist["telephone"] . '"/> Telephone <br/>
    <input type="text" name="mobile" value="' . $this->artist["mobile"] . '"> Mobile <br/>
    <input type="text" name="email" value="' . $this->artist["email"] . '"/> Email <br/>
    <input type="text" name="website" value="' . $this->artist["website"] . '"/> Website <br/>                                                  
    <input type="password" name="password"/> Password <br/>
    <br/><br/>
    <p>More iformatiom</p>                
    <br/>
    <br/>
    Art Form (select from the following)
    <br/>
    <input type="checkbox" name="artForm" value="2D"/> 2D <br/>
    <input type="checkbox" name="artForm" value="3DObject"/> 3D Object <br/>
    <input type="checkbox" name="artForm" value="publicArt"/> Public Art <br/>
    <input type="checkbox" name="artForm" value="drawing"/> Drawing <br/>
    <input type="checkbox" name="artForm" value="filmVideo"/> Film &amp; video <br/>
    <input type="checkbox" name="artForm" value="installation"/> Installation <br/>
    <input type="checkbox" name="artForm" value="mixedMedia"/> Mixed media <br/>
    <input type="checkbox" name="artForm" value="painting"/> Painting <br/>
    <input type="checkbox" name="artForm" value="performance"/> Performance <br/>
    <input type="checkbox" name="artForm" value="photography"/> Photography <br/>
    <input type="checkbox" name="artForm" value="print"/> Print <br/>
    <input type="checkbox" name="artForm" value="sculpture"/> Sculpture <br/>
    <input type="checkbox" name="artForm" value="sound"/> Sound <br/>
    <input type="checkbox" name="artForm" value="textiles"/> Textiles <br/>
    <input type="checkbox" name="artForm" value="jewellery"/> Jewellery <br/>
    <input type="checkbox" name="artForm" value="design"/> Design <br/>
    <br/>
    <br/>
    Activity
    <br/>
    <input type="checkbox" name="activity" value="exhibitions"/> Exhibitions <br/>
    <input type="checkbox" name="activity" value="commissions"/> Commissions <br/>
    <input type="checkbox" name="activity" value="residency"/> Residency <br/>
    <input type="checkbox" name="activity" value="selling"/> Selling <br/>
    <input type="checkbox" name="activity" value="workshopTeaching"/> Workshop/Teaching <br/>
    <input type="checkbox" name="activity" value="collaborations"/> Collaborations <br/>
    <input type="text" name="activity"/> Other <br/>
    <br/>
    <br/>
    <input type="submit" value="Update"/>';
?>