<p><img src="/images/find_artist_header.jpg" alt="Find an Artist" width="747" height="52" /></p>

<h2>welcome to the artist directory</h2>
<h3>"The Art House is approachable, cheerful and welcoming..."</h3><br />

<p id="alphabet">
<?php foreach(range('a','z') as $i): ?>
    <a href="/artists/index/filter-char/<?=$i?>"<?php if($this->showall == $i): ?> class="current"<?php endif; ?>><?=$i?></a> <?php if($i != 'z'): ?>|<?php endif; ?>
<?php endforeach; ?>
<?php if($this->showall): ?>
| <a href="/artists">show all</a>
<?php endif; ?>
</p>
<table cellspacing="0" id="artist_listing">
    <tr>
        <th><img src="/images/artist_name.jpg" alt="Name or Organisation" width="226" height="28" /></th>
        <th><img src="/images/artist_website.jpg" alt="Website" width="206" height="28" /></th>
        <th><img src="/images/artist_contact.jpg" alt="Contact" width="273" height="28" /></th>
    </tr>
    <?php foreach($this->artistsList as $artist): ?>
    <tr>
        <td><a href="/artists/biography/id/<?=$artist['id']?>"><?=$artist['first_name']?> <?=$artist['surname']?></a></td>
        <!-- <td><?=$artist['organisation']?></td> -->
        <td>
            <?php if($artist['website']): ?>
            <?php
            if(substr($artist['website'], 0, 4) != 'http') {
                $artist['website'] = sprintf('http://%s', $artist['website']);
            }
            ?>
            <a href="<?=$artist['website']?>" target="_blank">Visit website</a>
            <?php endif; ?>
        </td>
        <td>
            <?php if($artist['email']): ?>
                <a href="mailto:<?=$artist['email']?>">Email artist</a>
            <?php endif; ?>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
