<?php

    echo 'First Name - ' . $this->artist['first_name'];
    echo '<br/>';
    echo 'Surname - ' . $this->artist['surname'];
    echo '<br/>';
    echo 'Mobile - ' . $this->artist['mobile'];
    echo '<br/>';
    echo 'Telephone - ' . $this->artist['mobile'];
    echo '<br/>';
    echo 'Email - ' . $this->artist['email'];
    echo '<br/>';
    echo 'Website - ' . $this->artist['website'];
    echo '<br/>';
    if(!empty($this->artist['organisation'])): echo 'Organisation - ' . $this->artist['Organisation']; endif;
        
?>