<p><img src="/images/artist_header.jpg" alt="Artist" width="747" height="52" /></p>

<h2 class="artistname"><?=$this->artist['first_name']?> <?=$this->artist['surname']?></h2>

<p id="artist_nav"><a href="/artists/biography/id/<?=$this->artist['id']?>"><img src="/images/artist_biography.jpg" alt="Biography" width="177" height="28" /></a> <a href="/artists/news/id/<?=$this->artist['id']?>"><img src="/images/artist_news.jpg" alt="News" width="177" height="28" /></a> <a href="/artists/viewartist/id/<?=$this->artist['id']?>"><img src="/images/artist_artwork.jpg" alt="Artwork" width="177" height="28" /></a></p>

<form method="post" action="/artists/savenews/" enctype="multipart/form-data">      
    <input type="text" name="news_id" value="<?=$this->artistNews["news_id"];?>"/>
    <ul class="form">
        <li>
            <label class="desc">Title</label>
            <input type="text" name="title" value="<?php $this->artistNews["title"];?>"/>
        </li>
        <li>
            <label class="desc">Current Image</label>
            <img src="/images/artist_uploads/<?=$this->artist['id']?>/<?=$this->artistNews["news_image"];?>" alt="<?=$this->artistWork["title"];?>">
        </li>
        <li>
            <label class="desc">Preview</label>
            <input type="text" name="preview" value="<?php $this->artistNews["preview"];?>"/>
        </li>
        <li>
            <label class="desc">Content</label>
            <textarea name="content"><?php $this->artistNews["content"];?></textarea>
        </li>
        <li>
            <input type="submit" name="submitbutton" value="Create"/>
        </li>
    </ul>

</form>