    <?php if(count($this->blog_posts)): ?>
        <?php foreach($this->blog_posts as $post): ?>
            <div id="blogListImage">
<a href="/blog/view/<?=$post['post_id']?>"><img src="/images/blogimages/<?=$post['post_image']?>" width="138" alt="<?=$post['post_title']?>" /></a></div><!-- end id="blogListImage" -->
<div id="blogListContentMain">
<h2><a href="/blog/view/<?=$post['post_id']?>"><?=$post['post_title']?></a></h2>
<p><?=$post['post_summary']?><a style="font-weight: bold;" href="/blog/view/<?=$post['post_id']?>"> Read more...</a></p>
<p style="margin-bottom: 0px;">Article Posted by The Art House - <?=date('d M Y', strtotime($post['date_added']))?></p>
</div><!-- end id="blogListContent" -->
<div id="clear"></div>
        <?php endforeach; ?>
    <?php endif; ?>
