<?php
$name      = isset($this->formdata['data']['name']) ? $this->formdata['data']['name'] : '';
$email     = isset($this->formdata['data']['email']) ? $this->formdata['data']['email'] : '';
$company   = isset($this->formdata['data']['company']) ? $this->formdata['data']['company'] : '';
$telephone = isset($this->formdata['data']['telephone']) ? $this->formdata['data']['telephone'] : '';
$enquiry   = isset($this->formdata['data']['enquiry']) ? $this->formdata['data']['enquiry'] : '';
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?=$this->metaTitle?></title>
<meta name="keywords" content="<?=$this->metaKeywords?>" />
<meta name="description" content="<?=$this->metaDescription?>" />
<link rel="shortcut icon" href="/images/GV_ICON.ico" />
<link rel="stylesheet" type="text/css" href="/css/stylesheet.css" />
<link href="jquery.tweet.css" media="all" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" href="/css/ui-lightness/jquery-ui-1.8.13.custom.css" />
<script type="text/javascript" src="/js/jquery-1.4.4.js"></script>
<script type="text/javascript" src="/js/jquery-ui-1.8.13.custom.min.js"></script>
<script type="text/javascript" src="/js/cookie.js"></script>
<script type="text/javascript" src="/js/changestyle.js"></script>
<script type="text/javascript" src="/js/fontsize_slider.js"></script>
<script type="text/javascript" src="/js/jquery.tweet.js"></script>
<?php foreach ($this->css as $css):?>
    <link rel="stylesheet" type="text/css" href="<?=htmlentities($css, ENT_QUOTES, 'UTF-8')?>" />
<?php endforeach;?>
<?php foreach ($this->headJs as $headJs):?>
    <script src="<?=htmlentities($headJs, ENT_QUOTES, 'UTF-8')?>" type="text/javascript"></script>
<?php endforeach;?>

<script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>

<script type='text/javascript'>
    $(document).ready(function(){
        $(".tweet").tweet({
            username: "TheArtHouse2",
            join_text: "auto",
            avatar_size: null,
            count: 2,
            auto_join_text_default: "null",
            auto_join_text_ed: "null",
            auto_join_text_ing: "null",
            auto_join_text_reply: "null",
            auto_join_text_url: "null",
            loading_text: "loading tweets..."
        });
    });
</script>

</head>

<body>

<div id="mainContainer">

<div id="header">
<div id="headerLeft">
<a href="/"><img src="/images/LOGO.gif" alt="the art house" /></a>
</div><!-- end id="headerLeft" -->
<div id="headerRight">
<div id="headerRightLinks"><p><a href="/">Accessibility Guide</a> |</p>
</div><!-- end id="headerRightLinks" -->
<div id="display-ops">
            <p>Display Options<img src="/images/default.gif" alt="Default" width="16" height="17" class="first" /><img src="/images/clear.gif" alt="Clear" width="16" height="17" /><img src="/images/contrast.gif" alt="Contrast" width="15" height="17" /><span></span></p>
        </div><!-- end id="display-ops" -->
    <div id="slider_wrapper" style="overflow: hidden; clear: both;">
        <img src="/images/smaller_text.jpg" alt="Make text smaller" width="31" height="18" style="float: left;" id="smaller_text" />
        <div style="width: 135px; float: left; margin: 6px 2px 0 2px;">
           <div id="slider-range-min"></div>
        </div>
        <img src="/images/bigger_text.jpg" alt="Make text bigger" width="38" height="19" style="float: left;" id="bigger_text" />
        <p><a href="#" id="resetsize" style="margin-left: 10px;">reset font size</a></p>
    </div>
</div><!-- end id="headerRight" -->
</div><!-- end id="header" -->

<div id="topnav">
    <ul id="mainnav">
        <?=$this->nav?>
    </ul>
</div><!-- end id="topnav" -->

<div id="headerImage">
<div id="headerImagePhoto">
<a href="/"><img src="/images/headers/<?=$this->pageHeader?>" alt="<?=$this->pageCaption?>" /></a>
</div><!-- end id="headerImagePhoto" -->
<div id="headerImageCaption">
<h1><?=$this->pageCaption?></h1>
</div><!-- end id="headerImageCaption" -->
</div><!-- end id="headerImage" -->

<div id="contentContainer">

<div id="leftColumn">
<div id="subNavContainer">
<?php if(count($this->subpages)): ?>
            <ul id="subnav">
                <?php foreach($this->subpages as $subpageitem): ?>
                    <?php if($subpageitem['published'] == 1): ?>
                        <?php if($subpageitem['type'] == 'link'): ?>
                            <li><a href="<?=$subpageitem['permalink']?>"><?=$subpageitem['menu_text']?></a></li>
                        <?php else: ?>
                            <li><a href="/view/<?=$subpageitem['permalink']?>"><?=$subpageitem['menu_text']?></a></li>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
            <?php endif; ?>
</div><!-- end id="subNavContainer" -->
<div id="newsletter">
<a href="/"><img src="/images/SIGN_UP.gif" alt="sign up for our newsletter" /></a>
<a href="/"><img src="/images/FACEBOOK_FOLLOW.gif" alt="join our facebook group" /></a><br />
<a href="/"><img src="/images/TWITTER_FOLLOW.gif" alt="follow us on twitter" /></a>
</div><!-- end id="newsletter" -->
<div id="twitterFeed">
<img src="/images/TWEETS_FROM.gif" alt="tweets from the art house" />
<div class="tweet"></div>
</div><!-- end id="twitterFeed" -->
<div id="socialCounters">
<iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.the-arthouse.org.uk&amp;layout=button_count&amp;show_faces=false&amp;width=75&amp;action=like&amp;colorscheme=light&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:75px; height:21px;" allowTransparency="true"></iframe>
                <a href="http://twitter.com/share" class="twitter-share-button" data-url="http://www.the-arthouse.org.uk">Tweet</a>
</div><!-- end id="socialCounters" -->
</div><!-- end id="leftColumn" -->

<div id="rightColumn">
<?=$this->page_title ? '<h1>' . $this->page_title . '</h1>' : '';?>
<?php
            if ($this->contentView):
                if ($file = $this->_script($this->contentView)):
                        include $file;
                endif;
            else:
                echo $this->content;
            endif;
        ?><br />
        <?php if(count($this->formdata['errors'])): ?>
            <div id="errors">
                <p>
                    <?php foreach($this->formdata['errors'] as $error): ?>
                        <?=$error?><br />
                    <?php endforeach; ?>
                </p>
            </div><br />
        <?php endif; ?>
        <form method="post" action="/contact/senddetails/">
        	<div class="form_field"><label for="name" class="form_desc">Name:</label><input class="form_content" type="text" name="name" value="<?=$name?>" /> *</div>
        	<div class="form_field"><label for="email" class="form_desc">Email:</label><input class="form_content" type="text" name="email" value="<?=$email?>" /> *</div>
            <div class="form_field"><label for="company" class="form_desc">Company:</label><input class="form_content" type="text" name="company" value="<?=$company?>" /></div>
        	<div class="form_field"><label for="telephone" class="form_desc">Telephone:</label><input class="form_content" type="text" name="telephone" value="<?=$telephone?>" /> *</div>
           	<div class="form_field"><label for="enquiry" class="form_desc">Enquiry:</label><textarea class="form_content" type="text" name="enquiry" rows="3" cols="20" /><?=$enquiry?></textarea></div><br />
        	<div class="form_base">
        	   Please note: * indicates a required field<br />
        	   <input type="submit" name="submit_button" value="Submit"/>
            </div>
        </form>
</div><!-- end id="rightColumn" -->

<div id="clear"></div>
             

</div><!-- end id="contentContainer" -->

<div id="footer">
<div id="footerTop">
<div id="footerLeft">
<p>The Art House, Drury Lane, Wakefield, WF1 2TE  Tel: 01924 377740<br />Website designed and built by <a href="http://www.sugarcaneweb.co.uk">www.sugarcaneweb.co.uk</a></p>
</div><!-- end id="footerLeft" -->
<div id="footerRight">
<a href="http://www.artscouncil.org.uk/" target="_blank"><img src="/images/ACE.gif" alt="art council" /></a>
<a href="http://www.wyg.wyjs.org.uk/" target="_blank"><img src="/images/WYGRANTS.gif" alt="west yorkshire grants" /></a>
<a href="http://www.wakefield.gov.uk/default.htm" target="_blank"><img src="/images/WAKEFIELD.gif" alt="wakefield council" /></a>
</div><!-- end id="footerRight" -->
<div id="clear"></div>
</div><!-- end id="footerTop" -->
<div id="footerBottom">
</div><!-- end id="footerBottom" -->
</div><!-- end id="footer" -->

</div><!-- end id="mainContainer" -->

<?php foreach ($this->js as $js):?>
    <script src="<?=htmlentities($js, ENT_QUOTES, 'UTF-8')?>" type="text/javascript"></script>
<?php endforeach;?>

<div id="accesskeys" style="display: none;">
    <a href="/" accesskey="1">Home Page</a>
    <a href="/view/whats-on" accesskey="2">What's On</a>
    <a href="#" accesskey="3">Site Map</a>
    <a href="#" accesskey="4">Search</a>
    <a href="#" accesskey="5">FAQ</a>
    <a href="#" accesskey="6">Help</a>
    <a href="http://www.the-arthouse.org.uk/upload/file/complaints_policy_and_procedure_2010.doc" accesskey="7">Complaints Procedure</a>
    <a href="#" accesskey="8">Terms and Conditions</a>
    <a href="/artists" accesskey="9">Artists Directory</a>
    <a href="#" accesskey="0">Access Key Details</a>
    <a href="/view/space-for-hire" accesskey="S">Space to Hire</a>
    <a href="/view/get-involved" accesskey="G">Get Involved</a>
    <a href="/blog/1" accesskey="E">Equality & Quality</a>
</div>
</body>
</html>
