<?php
$name      = isset($this->formdata['data']['name']) ? $this->formdata['data']['name'] : '';
$email     = isset($this->formdata['data']['email']) ? $this->formdata['data']['email'] : '';
$company   = isset($this->formdata['data']['company']) ? $this->formdata['data']['company'] : '';
$telephone = isset($this->formdata['data']['telephone']) ? $this->formdata['data']['telephone'] : '';
$enquiry   = isset($this->formdata['data']['enquiry']) ? $this->formdata['data']['enquiry'] : '';
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?=$this->metaTitle?></title>
<meta name="keywords" content="<?=$this->metaKeywords?>" />
<meta name="description" content="<?=$this->metaDescription?>" />
<link rel="shortcut icon" href="/images/GV_ICON.ico" />
<link rel="stylesheet" type="text/css" href="/css/page-format.css"/>
<link rel="stylesheet" type="text/css" href="/css/stylesheet.css" />
<link rel="stylesheet" type="text/css" href="/css/topnav.css"/>
<?php foreach ($this->css as $css):?>
    <link rel="stylesheet" type="text/css" href="<?=htmlentities($css, ENT_QUOTES, 'UTF-8')?>" />
<?php endforeach;?>
<?php foreach ($this->headJs as $headJs):?>
    <script src="<?=htmlentities($headJs, ENT_QUOTES, 'UTF-8')?>" type="text/javascript"></script>
<?php endforeach;?>
</head>

<body>

<div id="mainContainer">

<div id="topnav">
<ul id="mainnav">
        <?=$this->nav?>
    </ul>
</div><!-- end id="topnav" -->

<div id="contentContainer">
<?=$this->page_title ? '<h1>' . $this->page_title . '</h1>' : '';?>
        <?php
            if ($this->contentView):
                if ($file = $this->_script($this->contentView)):
                        include $file;
                endif;
            else:
                echo $this->content;
            endif;
        ?>
        <?php if(count($this->formdata['errors'])): ?>
            <div id="errors">
                <p>
                    <?php foreach($this->formdata['errors'] as $error): ?>
                        <?=$error?><br />
                    <?php endforeach; ?>
                </p>
            </div><br />
        <?php endif; ?>
        <form method="post" action="/contact/senddetails/">
        	<div class="form_field"><label for="name" class="form_desc">Name:</label><input class="form_content" type="text" name="name" value="<?=$name?>" /> *</div>
        	<div class="form_field"><label for="email" class="form_desc">Email:</label><input class="form_content" type="text" name="email" value="<?=$email?>" /> *</div>
            <div class="form_field"><label for="company" class="form_desc">Company:</label><input class="form_content" type="text" name="company" value="<?=$company?>" /></div>
        	<div class="form_field"><label for="telephone" class="form_desc">Telephone:</label><input class="form_content" type="text" name="telephone" value="<?=$telephone?>" /> *</div>
           	<div class="form_field"><label for="enquiry" class="form_desc">Enquiry:</label><textarea class="form_content" type="text" name="enquiry" rows="3" cols="20" /><?=$enquiry?></textarea></div><br />
        	<div class="form_base">
        	   Please note: * indicates a required field<br />
        	   <input type="submit" name="submit_button" value="Submit"/>
            </div>
        </form>
</div><!-- end id="contentContainer" -->

<div id="subNavContainer">
<?php if(count($this->subpages)): ?>
            <ul id="subnav">
                <?php foreach($this->subpages as $subpageitem): ?>
                    <?php if($subpageitem['published'] == 1): ?>
                        <?php if($subpageitem['type'] == 'link'): ?>
                            <li><a href="<?=$subpageitem['permalink']?>"><?=$subpageitem['menu_text']?></a></li>
                        <?php else: ?>
                            <li><a href="/view/<?=$subpageitem['permalink']?>"><?=$subpageitem['menu_text']?></a></li>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
            <?php endif; ?>
</div><!-- end id="subNavContainer" -->

</div><!-- end id="mainContainer" -->

<?php foreach ($this->js as $js):?>
    <script src="<?=htmlentities($js, ENT_QUOTES, 'UTF-8')?>" type="text/javascript"></script>
<?php endforeach;?>
</body>
</html>