<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?=$this->metaTitle?></title>
<meta name="keywords" content="<?=$this->metaKeywords?>" />
<meta name="description" content="<?=$this->metaDescription?>" />
<link rel="shortcut icon" href="/images/GV_ICON.ico" />
<link rel="stylesheet" type="text/css" href="/css/stylesheet.css" />
<link href="jquery.tweet.css" media="all" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" href="/css/ui-lightness/jquery-ui-1.8.13.custom.css" />
<script type="text/javascript" src="/js/jquery-1.4.4.js"></script>
<script type="text/javascript" src="/js/jquery-ui-1.8.13.custom.min.js"></script>
<script type="text/javascript" src="/js/cookie.js"></script>
<script type="text/javascript" src="/js/changestyle.js"></script>
<script type="text/javascript" src="/js/fontsize_slider.js"></script>
<script type="text/javascript" src="/js/jquery.tweet.js"></script>
<?php foreach ($this->css as $css):?>
    <link rel="stylesheet" type="text/css" href="<?=htmlentities($css, ENT_QUOTES, 'UTF-8')?>" />
<?php endforeach;?>
<?php foreach ($this->headJs as $headJs):?>
    <script src="<?=htmlentities($headJs, ENT_QUOTES, 'UTF-8')?>" type="text/javascript"></script>
<?php endforeach;?>
<script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>
<script type='text/javascript'>
    $(document).ready(function(){
        $(".tweet").tweet({
            username: "sugarcaneweb",
            join_text: "auto",
            avatar_size: null,
            count: 2,
            auto_join_text_default: "null",
            auto_join_text_ed: "null",
            auto_join_text_ing: "null",
            auto_join_text_reply: "null",
            auto_join_text_url: "null",
            loading_text: "loading tweets..."
        });
    });
</script>
</head>

<body>

<div id="mainContainer">

<div id="header">
<div id="headerLeft">
<a href="/"><img src="/images/LOGO.gif" alt="the art house" /></a>
</div><!-- end id="headerLeft" -->
<div id="headerRight">
<div id="headerRightLinks"><p><a href="/">Accessibility Guide</a> |</p>
</div><!-- end id="headerRightLinks" -->
<div id="display-ops">
            <p>Display Options<img src="/images/default.gif" alt="Default" width="16" height="17" class="first" /><img src="/images/clear.gif" alt="Clear" width="16" height="17" /><img src="/images/contrast.gif" alt="Contrast" width="15" height="17" /><span></span></p>
        </div><!-- end id="display-ops" -->
    <div id="slider_wrapper" style="overflow: hidden; clear: both;">
        <img src="images/smaller_text.jpg" alt="Make text smaller" width="31" height="18" style="float: left;" id="smaller_text" />
        <div style="width: 135px; float: left; margin: 6px 2px 0 2px;">
           <div id="slider-range-min"></div>
        </div>
        <img src="images/bigger_text.jpg" alt="Make text bigger" width="38" height="19" style="float: left;" id="bigger_text" />
    </div>
</div><!-- end id="headerRight" -->
</div><!-- end id="header" -->

<div id="topnav">
    <ul id="mainnav">
        <?=$this->nav?>
    </ul>
</div><!-- end id="topnav" -->

<div id="headerImage">
<div id="headerImagePhoto">
<a href="/"><img src="/images/HEADER.jpg" alt="" /></a>
</div><!-- end id="headerImagePhoto" -->
<div id="headerImageCaption">
<h1>Equality and Quality in Visual Arts...</h1>
</div><!-- end id="headerImageCaption" -->
</div><!-- end id="headerImage" -->

<div id="contentContainer">
<!-- Content not needed for home page
<?=$this->page_title ? '<h1>' . $this->page_title . '</h1>' : '';?>
<?php
            if ($this->contentView):
                if ($file = $this->_script($this->contentView)):
                        include $file;
                endif;
            else:
                echo $this->content;
            endif;
        ?>
-->

<div id="leftColumn">
<div id="newsletter">
<a href="/"><img src="/images/SIGN_UP.gif" alt="sign up for our newsletter" /></a>
<a href="/"><img src="/images/FACEBOOK_FOLLOW.gif" alt="join our facebook group" /></a><br />
<a href="/"><img src="/images/TWITTER_FOLLOW.gif" alt="follow us on twitter" /></a>
</div><!-- end id="newsletter" -->
<div id="twitterFeed">
<img src="/images/TWEETS_FROM.gif" alt="tweets from the art house" />
<div class="tweet"></div>
</div><!-- end id="twitterFeed" -->
<div id="socialCounters">
<iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.the-arthouse.org.uk&amp;layout=button_count&amp;show_faces=false&amp;width=75&amp;action=like&amp;colorscheme=light&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:75px; height:21px;" allowTransparency="true"></iframe>
                <a href="http://twitter.com/share" class="twitter-share-button" data-url="http://www.the-arthouse.org.uk">Tweet</a>
</div><!-- end id="socialCounters" -->
</div><!-- end id="leftColumn" -->

<div id="rightColumn">
<div id="rightColumnLeft">
<div class="rightColumnCalloutTop">
<a href="/"><h3 class="rightColumnHome">get involved</h3></a>
</div><!-- end id="rightColumnCalloutTop" -->
<div class="rightColumnCalloutMiddle">
<a href="/"><img src="/images/CALLOUT_1.jpg" alt="get involved" /></a>
</div><!-- end id="rightColumnCalloutMiddle" -->
<div class="rightColumnCalloutBottom">
<a href="/"><p class="rightColumnHome">More about becoming a patron, artist member or facility member...</p></a>
</div><!-- end id="rightColumnCalloutBottom" -->
<div class="rightColumnCalloutTop">
<a href="/"><h3 class="rightColumnHome">equality & quality</h3></a>
</div><!-- end id="rightColumnCalloutTop" -->
<div class="rightColumnCalloutMiddle">
<a href="/"><img src="/images/CALLOUT_4.jpg" alt="equality & quality" /></a>
</div><!-- end id="rightColumnCalloutMiddle" -->
<div class="rightColumnCalloutBottom">
<a href="/"><p class="rightColumnHome">This section is all about dialogue and consultancy...</p></a>
</div><!-- end id="rightColumnCalloutBottom" -->
</div><!-- end id="rightColumnLeft" -->
<div id="rightColumnMiddle">
<div class="rightColumnCalloutTop">
<a href="/"><h3 class="rightColumnHome">for artists</h3></a>
</div><!-- end id="rightColumnCalloutTop" -->
<div class="rightColumnCalloutMiddle">
<a href="/"><img src="/images/CALLOUT_2.jpg" alt="for artists" /></a>
</div><!-- end id="rightColumnCalloutMiddle" -->
<div class="rightColumnCalloutBottom">
<a href="/"><p class="rightColumnHome">Find out about what’s on, our facilities, residencies and more...</p></a>
</div><!-- end id="rightColumnCalloutBottom" -->
<div class="rightColumnCalloutTop">
<a href="/"><h3 class="rightColumnHome">find an artist</h3></a>
</div><!-- end id="rightColumnCalloutTop" -->
<div class="rightColumnCalloutMiddle">
<a href="/"><img src="/images/CALLOUT_5.jpg" alt="find an artist" /></a>
</div><!-- end id="rightColumnCalloutMiddle" -->
<div class="rightColumnCalloutBottom">
<a href="/"><p class="rightColumnHome">Here you’l find all the artists who are members in a directory...</p></a>
</div><!-- end id="rightColumnCalloutBottom" -->
</div><!-- end id="rightColumnMiddle" -->
<div id="rightColumnRight">
<div class="rightColumnCalloutTop">
<a href="/"><h3 class="rightColumnHome">space for hire</h3></a>
</div><!-- end id="rightColumnCalloutTop" -->
<div class="rightColumnCalloutMiddle">
<a href="/"><img src="/images/CALLOUT_3.jpg" alt="space for hire" /></a>
</div><!-- end id="rightColumnCalloutMiddle" -->
<div class="rightColumnCalloutBottom">
<a href="/"><p class="rightColumnHome">Unprecedented accessibility, artist studios, office space and more...</p></a>
</div><!-- end id="rightColumnCalloutBottom" -->
<div class="rightColumnCalloutTop">
<a href="/"><h3 class="rightColumnHome">what's on</h3></a>
</div><!-- end id="rightColumnCalloutTop" -->
<div class="rightColumnCalloutMiddle">
<a href="/"><img src="/images/CALLOUT_6.jpg" alt="what's on" /></a>
</div><!-- end id="rightColumnCalloutMiddle" -->
<div class="rightColumnCalloutBottom">
<a href="/"><p class="rightColumnHome">All about events, courses and the Art House community groups...</p></a>
</div><!-- end id="rightColumnCalloutBottom" -->
</div><!-- end id="rightColumnRight" -->
</div><!-- end id="rightColumn" -->

<div id="clear"></div>
        
<div id="blogHome">
<h1>follow our blog</h1>
<?php if(count($this->blogposts)): ?>
	<?php foreach($this->blogposts as $blogposts): ?>
	<div id="blogListImage">
<a href="/blog/view/<?=$blogposts['post_id']?>"><img src="/images/blogimages/<?=$blogposts['post_image']?>" width="138" alt="<?=$blogposts['post_title']?>" /></a></div><!-- end id="blogListImage" -->
<div id="blogListContent">
<h2><a href="/blog/view/<?=$blogposts['post_id']?>"><?=$blogposts['post_title']?></a></h2>
<p><?=$blogposts['post_summary']?><a style="font-weight: bold;" href="/blog/view/<?=$blogposts['post_id']?>"> Read more...</a></p>
<p style="margin-bottom: 0px;">Article Posted by The Art House - <?=date('d M Y', strtotime($blogposts['date_added']))?></p>
</div><!-- end id="blogListContent" -->
<div id="clear"></div>
<?php endforeach; ?>
<?php else: ?>
        <p>No blog posts found</p>
    <?php endif; ?>
</div><!-- end id="blogHome" -->        

</div><!-- end id="contentContainer" -->

<div id="footer">
<div id="footerTop">
<div id="footerLeft">
<p>The Art House, Drury Lane, Wakefield, WF1 2TE  Tel: 01924 377740<br />Website designed and built by <a href="http://www.sugarcaneweb.co.uk">www.sugarcaneweb.co.uk</a></p>
</div><!-- end id="footerLeft" -->
<div id="footerRight">
<a href="/"><img src="/images/FOOTER_LOGO.gif" alt="" /></a>
<a href="/"><img src="/images/FOOTER_LOGO.gif" alt="" /></a>
<a href="/"><img src="/images/FOOTER_LOGO.gif" alt="" /></a>
</div><!-- end id="footerRight" -->
<div id="clear"></div>
</div><!-- end id="footerTop" -->
<div id="footerBottom">
</div><!-- end id="footerBottom" -->
</div><!-- end id="footer" -->

</div><!-- end id="mainContainer" -->

<?php foreach ($this->js as $js):?>
    <script src="<?=htmlentities($js, ENT_QUOTES, 'UTF-8')?>" type="text/javascript"></script>
<?php endforeach;?>
</body>
</html>
