<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?=$this->metaTitle?></title>
<meta name="keywords" content="<?=$this->metaKeywords?>" />
<meta name="description" content="<?=$this->metaDescription?>" />
<link rel="stylesheet" type="text/css" href="/css/stylesheet.css" />
<?php foreach ($this->css as $css):?>
    <link rel="stylesheet" type="text/css" href="<?=htmlentities($css, ENT_QUOTES, 'UTF-8')?>" />
<?php endforeach;?>
<?php foreach ($this->headJs as $headJs):?>
    <script src="<?=htmlentities($headJs, ENT_QUOTES, 'UTF-8')?>" type="text/javascript"></script>
<?php endforeach;?>
</head>

<body>

<p style="background-color: #000000;"><img src="/images/antodev.png" alt="antodev" width="184" height="61" /></p>
<div id="mainContainer">
    <ul id="mainnav">
        <?=$this->nav?>
    </ul>
        
    <?php if(count($this->subpages)): ?>
    <div id="subNavContainer">
        <ul id="subnav">
            <?php foreach($this->subpages as $subpageitem): ?>
                <?php if($subpageitem['published'] == 1): ?>
                    <?php if($subpageitem['type'] == 'link'): ?>
                        <li><a href="<?=$subpageitem['permalink']?>"><?=$subpageitem['menu_text']?></a></li>
                    <?php else: ?>
                        <li><a href="/view/<?=$subpageitem['permalink']?>"><?=$subpageitem['menu_text']?></a></li>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div><!-- end id="subNavContainer" -->
    <?php endif; ?>
    
    <div id="contentContainer">
        <?=$this->page_title ? '<h1>' . $this->page_title . '</h1>' : '';?>
        <?php
            if ($this->contentView):
                if ($file = $this->_script($this->contentView)):
                        include $file;
                endif;
            else:
                echo $this->content;
            endif;
        ?>
    </div>
</div>

<?php foreach ($this->js as $js):?>
    <script src="<?=htmlentities($js, ENT_QUOTES, 'UTF-8')?>" type="text/javascript"></script>
<?php endforeach;?>
</body>
</html>