<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?=$this->metaTitle?></title>
<meta name="keywords" content="<?=$this->metaKeywords?>" />
<meta name="description" content="<?=$this->metaDescription?>" />
<link rel="shortcut icon" href="/images/GV_ICON.ico" />
<link rel="stylesheet" type="text/css" href="/css/stylesheet.css" />
<link href="jquery.tweet.css" media="all" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="/js/jquery-1.4.4.js"></script>
<script type="text/javascript" src="/js/changestyle.js"></script>
<script type="text/javascript" src="/js/jquery.tweet.js"></script>
<?php foreach ($this->css as $css):?>
    <link rel="stylesheet" type="text/css" href="<?=htmlentities($css, ENT_QUOTES, 'UTF-8')?>" />
<?php endforeach;?>
<?php foreach ($this->headJs as $headJs):?>
    <script src="<?=htmlentities($headJs, ENT_QUOTES, 'UTF-8')?>" type="text/javascript"></script>
<?php endforeach;?>

<script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>

<script type='text/javascript'>
    $(document).ready(function(){
        $(".tweet").tweet({
            username: "sugarcaneweb",
            join_text: "auto",
            avatar_size: null,
            count: 2,
            auto_join_text_default: "null",
            auto_join_text_ed: "null",
            auto_join_text_ing: "null",
            auto_join_text_reply: "null",
            auto_join_text_url: "null",
            loading_text: "loading tweets..."
        });
    });
</script>

</head>

<body>

<div id="mainContainer">

<div id="header">
<div id="headerLeft">
<a href="/"><img src="/images/LOGO.gif" alt="the art house" /></a>
</div><!-- end id="headerLeft" -->
<div id="headerRight">
<div id="headerRightLinks"><p><a href="/">Accessibility Guide</a> |</p>
</div><!-- end id="headerRightLinks" -->
<div id="display-ops">
            <p>Display Options<img src="/images/default.gif" alt="Default" width="16" height="17" class="first" /><img src="/images/clear.gif" alt="Clear" width="16" height="17" /><img src="/images/contrast.gif" alt="Contrast" width="15" height="17" /><span></span></p>
        </div><!-- end id="display-ops" -->
</div><!-- end id="headerRight" -->
</div><!-- end id="header" -->

<div id="topnav">
    <ul id="mainnav">
        <?=$this->nav?>
    </ul>
</div><!-- end id="topnav" -->

<div id="headerImage">
<div id="headerImagePhoto">
<a href="/"><img src="/images/HEADER.jpg" alt="" /></a>
</div><!-- end id="headerImagePhoto" -->
<div id="headerImageCaption">
<h1>Equality and Quality in Visual Arts...</h1>
</div><!-- end id="headerImageCaption" -->
</div><!-- end id="headerImage" -->

<div id="contentContainer">
<!-- Content not needed for home page
<?=$this->page_title ? '<h1>' . $this->page_title . '</h1>' : '';?>
<?php
            if ($this->contentView):
                if ($file = $this->_script($this->contentView)):
                        include $file;
                endif;
            else:
                echo $this->content;
            endif;
        ?>
-->

<div id="leftColumn">
<div id="newsletter">
<a href="/"><img src="/images/SIGN_UP.gif" alt="sign up for our newsletter" /></a>
<a href="/"><img src="/images/FACEBOOK_FOLLOW.gif" alt="join our facebook group" /></a><br />
<a href="/"><img src="/images/TWITTER_FOLLOW.gif" alt="follow us on twitter" /></a>
</div><!-- end id="newsletter" -->
<div id="twitterFeed">
<img src="/images/TWEETS_FROM.gif" alt="tweets from the art house" />
<div class="tweet"></div>
</div><!-- end id="twitterFeed" -->
<div id="socialCounters">
<iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.the-arthouse.org.uk&amp;layout=button_count&amp;show_faces=false&amp;width=75&amp;action=like&amp;colorscheme=light&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:75px; height:21px;" allowTransparency="true"></iframe>
                <a href="http://twitter.com/share" class="twitter-share-button" data-url="http://www.the-arthouse.org.uk">Tweet</a>
</div><!-- end id="socialCounters" -->
</div><!-- end id="leftColumn" -->

<div id="rightColumn">
    <div id="artistShow">Artist</div>
    <div id="patronShow">Patron</div>
    <div id="artist" style="display: none;">
    
        <h1>Artist Signup</h1>

        <form method="" action="post">
            <p>I would like to join the art house as </p>
            <input type="radio" class="membership" name="membership" value="individual" /> A individual artist: <strong>&pound;15.00</strong> (<strong>&pound;7.50</strong> concessionary membership, not available to international members)<br />
            <input type="radio" class="membership" name="membership" value="pair" /> Two people at the same address: <strong>&pound;20.00</strong><br />
            <input type="radio" class="membership" name="membership" value="group" /> As a Group: <strong>&pound;32.50</strong> (For group membership, please give the name of the person you would like us to address correspondence to)<br />
            <div id="individual" class="information" style="display: none;">        
                <p>Individual information</p>        
                    <input type="text" name="name"/> Name <br/>
                    <input type="text" name="addressOne"/> Address line one <br/>
                    <input type="text" name="addressTwo"/> Address line two <br/>
                    <input type="text" name="city"/> City <br/>
                    <input type="text" name="county"/> County <br/>
                    <input type="text" name="country"/> Country <br/>
                    <input type="text" name="telephone"/> Telephone <br/>
                    <input type="text" name="mobile"/> Mobile <br/>
                    <input type="text" name="email"/> Email <br/>
                    <input type="text" name="website"/> Website <br/>                        
            </div>        
            <div id="pair" class="information" style="display: none;">    
                <p>Individual one information</p>        
                    <input type="text" name="nameFirst"/> Name <br/>
                    <input type="text" name="mobileFirst"/> Mobile <br/>
                    <input type="text" name="emailFirst"/> Email <br/>
                    <input type="text" name="websiteFirst"/> Website <br/>        
                <p>Individual two information</p>        
                    <input type="text" name="nameSecond"/> Name <br/>            
                    <input type="text" name="mobileSecond"/> Mobile <br/>
                    <input type="text" name="emailSecond"/> Email <br/>
                    <input type="text" name="websiteSecond"/> Website <br/>            
                <p>Address</p>        
                    <input type="text" name="addressOne"/> Address line one <br/>
                    <input type="text" name="addressTwo"/> Address line two <br/>
                    <input type="text" name="city"/> City <br/>
                    <input type="text" name="county"/> County <br/>
                    <input type="text" name="country"/> Country <br/>
                    <input type="text" name="telephoneFirst"/> Telephone <br/>                        
            </div>

            <div id="group" class="information" style="display: none;">                
                <p>Group information</p>        
                    <input type="text" name="groupName"/> Group name <br/>
                    <input type="text" name="name"/> Name <br/>
                    <input type="text" name="addressOne"/> Address line one <br/>
                    <input type="text" name="addressTwo"/> Address line two <br/>
                    <input type="text" name="city"/> City <br/>
                    <input type="text" name="county"/> County <br/>
                    <input type="text" name="country"/> Country <br/>
                    <input type="text" name="telephone"/> Telephone <br/>
                    <input type="text" name="mobile"/> Mobile <br/>
                    <input type="text" name="email"/> Email <br/>
                    <input type="text" name="website"/> Website <br/>                       
            </div>
            <div id="generic" style="display: none;">
                <p>More iformatiom</p>
                    How did you hear about The Art House?
                    <br/>
                    <select name="hear">
                        <option value="leaflet">Leaflet</option>
                        <option value="wordofmouth">Word of mouth</option>
                        <option value="website">Website</option>
                        <option value="press">Press</option>
                        <option value="other">Other</option>
                    </select>
                    <br/>
                    <br/>
                    Art Form (select from the following)
                    <br/>
                    <input type="checkbox" name="artForm" value="2D"/> 2D <br/>
                    <input type="checkbox" name="artForm" value="3DObject"/> 3D Object <br/>
                    <input type="checkbox" name="artForm" value="publicArt"/> Public Art <br/>
                    <input type="checkbox" name="artForm" value="drawing"/> Drawing <br/>
                    <input type="checkbox" name="artForm" value="filmVideo"/> Film &amp; video <br/>
                    <input type="checkbox" name="artForm" value="installation"/> Installation <br/>
                    <input type="checkbox" name="artForm" value="mixedMedia"/> Mixed media <br/>
                    <input type="checkbox" name="artForm" value="painting"/> Painting <br/>
                    <input type="checkbox" name="artForm" value="performance"/> Performance <br/>
                    <input type="checkbox" name="artForm" value="photography"/> Photography <br/>
                    <input type="checkbox" name="artForm" value="print"/> Print <br/>
                    <input type="checkbox" name="artForm" value="sculpture"/> Sculpture <br/>
                    <input type="checkbox" name="artForm" value="sound"/> Sound <br/>
                    <input type="checkbox" name="artForm" value="textiles"/> Textiles <br/>
                    <input type="checkbox" name="artForm" value="jewellery"/> Jewellery <br/>
                    <input type="checkbox" name="artForm" value="design"/> Design <br/>
                    <br/>
                    <br/>
                    Activity
                    <br/>
                    <input type="checkbox" name="activity" value="exhibitions"/> Exhibitions <br/>
                    <input type="checkbox" name="activity" value="commissions"/> Commissions <br/>
                    <input type="checkbox" name="activity" value="residency"/> Residency <br/>
                    <input type="checkbox" name="activity" value="selling"/> Selling <br/>
                    <input type="checkbox" name="activity" value="workshopTeaching"/> Workshop/Teaching <br/>
                    <input type="checkbox" name="activity" value="collaborations"/> Collaborations <br/>
                    <input type="text" name="activity"/> Other <br/>
                    <br/>
                    <br/>
                <input type="submit" value="Apply"/>                      
            </div>
        </form>
        
    </div><!-- end id-"artist" -->
    <div id="patron" style="display: none;">
    
        <h1>Patron Signup</h1>

        <form method="" action="post">  
            <p>Personal information</p>        
                <input type="text" name="name"/> Name <br/>
                <input type="text" name="addressOne"/> Address line one <br/>
                <input type="text" name="addressTwo"/> Address line two <br/>
                <input type="text" name="city"/> City <br/>
                <input type="text" name="county"/> County <br/>
                <input type="text" name="country"/> Country <br/>
                <input type="text" name="telephone"/> Telephone <br/>
                <input type="text" name="mobile"/> Mobile <br/>
                <input type="text" name="email"/> Email <br/>
                <input type="text" name="website"/> Website <br/>                                                
            <p>More iformatiom</p>
                How did you hear about The Art House?
                <br/>
                <select name="hear">
                    <option value="leaflet">Leaflet</option>
                    <option value="wordofmouth">Word of mouth</option>
                    <option value="website">Website</option>
                    <option value="press">Press</option>
                    <option value="other">Other</option>
                </select>
                <br/>
                <br/>
                <input type="radio" name="terms" value="agree" id="agree"/>
                I wish to become a patron  and agree to pay the membership fee of £xx per annum and agree to the terms and conditions of membership (link to terms and conditions)
                <br/>
                <br/>
                <input type="submit" value="Apply" id="submitPatron"/>                                  
        </form>
        
    </div><!-- end id-"patron"-->    
          
</div><!-- end id="rightColumn" -->

<div id="clear"></div>
        
<div id="blogHome">
<h1>follow our blog</h1>
<?php if(count($this->blogposts)): ?>
	<?php foreach($this->blogposts as $blogposts): ?>
	<div id="blogListImage">
<a href="/blog/view/<?=$blogposts['post_id']?>"><img src="/images/blogimages/<?=$blogposts['post_image']?>" width="138" alt="<?=$blogposts['post_title']?>" /></a></div><!-- end id="blogListImage" -->
<div id="blogListContent">
<h2><a href="/blog/view/<?=$blogposts['post_id']?>"><?=$blogposts['post_title']?></a></h2>
<p><?=$blogposts['post_summary']?><a style="font-weight: bold;" href="/blog/view/<?=$blogposts['post_id']?>"> Read more...</a></p>
<p style="margin-bottom: 0px;">Article Posted by The Art House - <?=date('d M Y', strtotime($blogposts['date_added']))?></p>
</div><!-- end id="blogListContent" -->
<div id="clear"></div>
<?php endforeach; ?>
<?php else: ?>
        <p>No blog posts found</p>
    <?php endif; ?>
</div><!-- end id="blogHome" -->        

</div><!-- end id="contentContainer" -->

<div id="footer">
<div id="footerTop">
<div id="footerLeft">
<p>The Art House, Drury Lane, Wakefield, WF1 2TE  Tel: 01924 377740<br />Website designed and built by <a href="http://www.sugarcaneweb.co.uk">www.sugarcaneweb.co.uk</a></p>
</div><!-- end id="footerLeft" -->
<div id="footerRight">
<a href="/"><img src="/images/FOOTER_LOGO.gif" alt="" /></a>
<a href="/"><img src="/images/FOOTER_LOGO.gif" alt="" /></a>
<a href="/"><img src="/images/FOOTER_LOGO.gif" alt="" /></a>
</div><!-- end id="footerRight" -->
<div id="clear"></div>
</div><!-- end id="footerTop" -->
<div id="footerBottom">
</div><!-- end id="footerBottom" -->
</div><!-- end id="footer" -->

</div><!-- end id="mainContainer" -->

<?php foreach ($this->js as $js):?>
    <script src="<?=htmlentities($js, ENT_QUOTES, 'UTF-8')?>" type="text/javascript"></script>
<?php endforeach;?>

<script type="text/javascript">
    
    $(document).ready(function(){
       
       $('#patronShow').click(function(){
           $('#patron').show();
           $('#artist').hide();
       });
       
       $('#artistShow').click(function(){
           $('#patron').hide();
           $('#artist').show();
       });
       
       $('input.membership').click(function(){
          
          var divShow = $(this).attr('value');
          
          $('.information').hide();
          $('#' + divShow).show();
          $('#generic').show();
           
       });
        
    });
    
</script>
    
</body>
</html>
